{% set name = "opentelemetry-instrumentation-grpc" %}
{% set version = "0.51b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_grpc-{{ version }}.tar.gz
  sha256: 70931c1a9f5fdde9d4498762fd98db41ad119a7e08e432052ff83a6495bf8ac5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.51b0
    - opentelemetry-sdk ~=1.12
    - opentelemetry-semantic-conventions ==0.51b0
    - wrapt <2.0.0,>=1.0.0
    # - grpcio ~=1.27
    # - grpcio ~=1.27
    # - grpcio ~=1.27
    # - grpcio >=1.42.0
    # - grpcio >=1.42.0
    # - grpcio >=1.42.0
    # - grpcio >=1.42.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-grpc
  summary: OpenTelemetry gRPC instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
