{% set name = "opentelemetry-instrumentation-grpc" %}
{% set version = "0.46b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_grpc-{{ version }}.tar.gz
  sha256: 9c5738592cf82672805099826b676d352324b54e03f9ac72a1368ba0605d6ff9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.46b0
    - opentelemetry-sdk ~=1.12
    - opentelemetry-semantic-conventions ==0.46b0
    - wrapt <2.0.0,>=1.0.0
    # - grpcio ~=1.27

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-grpc
  summary: OpenTelemetry gRPC instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
